HELP_TEXT = {
    "Select a model": "Select a language model to use for generating text. The 'text-davinci-003' model is the most capable and expensive, while 'gpt-3.5-turbo-0301' is a cheaper and less capable model.",
    "LLM Temperature": "Controls the randomness of the generated text. Higher values lead to more random text, while lower values lead to more predictable text.",
    "Max Tokens": "The maximum number of tokens (words or subwords) that the language model can generate. Larger values lead to longer text.",
    "Frequency Penalty": "Controls how much the language model avoids repeating the same phrases or patterns in the generated text.",
    "Presence Penalty": "Controls how much the language model avoids using words or phrases that were already used in the input text or previous generations.",
    "Select text splitter": "Select a text splitter to use for splitting the input text into smaller chunks. 'RecursiveCharacterTextSplitter' is the default and recommended option, while 'CharacterTextSplitter' is faster but may produce lower quality results.",
    "Chunk size": "The size of each chunk of text that is generated by the language model. Larger values lead to longer chunks and fewer overall chunks.",
    "Chunk overlap": "The amount of overlap between adjacent chunks of text. Larger values lead to more overlap and smoother transitions between chunks, but may also result in more repetition and less diversity in the generated text."
}
